version: '3.4'
services:
  netbox-node1: &netbox-node1
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == node1]
    depends_on:
    - pgpool-0
    - redis-sentinel-node1
    - redis-sentinel-cache-node1
    - netbox-wk-node1
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - netbox-config:/etc/netbox:z
    - netbox-static:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-wk-node1:
    <<: *netbox-node1
    depends_on:
    - redis-node1
    - redis-node2
    - redis-node3
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  netbox-node2: &netbox-node2
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == node2]
    depends_on:
    - pgpool-1
    - redis-sentinel-node2
    - redis-sentinel-cache-node2
    - netbox-wk-node2
    env_file: env/netbox1.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - netbox-config:/etc/netbox:z
    - netbox-static:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-wk-node2:
    <<: *netbox-node2
    depends_on:
    - redis-node1
    - redis-node2
    - redis-node3
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  netbox-node3: &netbox-node3
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == node3]
    depends_on:
    - pgpool-2
    - redis-sentinel-node3
    - redis-sentinel-cache-node3
    - netbox-wk-node3
    env_file: env/netbox2.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - netbox-config:/etc/netbox:z
    - netbox-static:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-wk-node3:
    <<: *netbox-node3
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  nginx-reverse-lb:
    image: nginx:1.20
    deploy:
      mode: global
    ports:
      - 80:80
      - 443:443
    volumes:
    - netbox-static:/opt/netbox/netbox/static/:z,ro
    - ./nginx-cert/conf.d:/etc/nginx/conf.d:z,ro
    - ./nginx-cert/ssl:/etc/nginx/ssl:z,ro

volumes:
  netbox-media-files:
    driver: local
  netbox-config:
    driver: local
  netbox-static:
    driver: local