version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:${VERSION-latest}
    depends_on:
    - pgpool
    - redis-sentinel
    - redis-sentinel-cache
    - netbox-worker
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - netbox-config:/etc/netbox:z
    ports:
    - "8080"
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []

  # postgres
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:13
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:13
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pg-2:
    image: docker.io/bitnami/postgresql-repmgr:13
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
  pgpool:
    image: docker.io/bitnami/pgpool:4
    ports:
      - 5432:5432
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  # redis

  redis:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=Viethung1008@
    volumes:
    - netbox-redis-data:/bitnami/redis/data

  redis-slave-0:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis
    volumes:
    - netbox-redis_0-data:/bitnami/redis/data

  redis-slave-1:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis
    volumes:
    - netbox-redis_1-data:/bitnami/redis/data
  
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26379:26379'
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26380:26379'

  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26381:26379'
# redis cache 
  redis-cache-master:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=Viethung1008@

  redis-cache-slave-1:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-cache-master

  redis-cache-slave-0:
    image: 'bitnami/redis:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-cache-master

  redis-sentinel-cache:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26382:26379'
  redis-sentinel-cache-1:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26383:26379'
  redis-sentinel-cache-2:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26384:26379'

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
  netbox-config:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis_0-data:
    driver: local
  netbox-redis_1-data:
    driver: local
