version: '3.4'
services:
  netbox: &netbox
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    depends_on:
    - pgpool-0
    - redis-sentinel
    - redis-sentinel-cache
    - netbox-worker
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    - netbox-config:/etc/netbox:z
    - netbox-static1:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis-master
    - redis-slave-0
    - redis-slave-1
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  netbox1: &netbox1
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    depends_on:
    - pgpool-1
    - redis-sentinel-1
    - redis-sentinel-cache-1
    - netbox-worker1
    env_file: env/netbox1.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files1:/opt/netbox/netbox/media:z
    - netbox-config1:/etc/netbox:z
    - netbox-static2:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-worker1:
    <<: *netbox1
    depends_on:
    - redis-master
    - redis-slave-0
    - redis-slave-1
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  netbox2: &netbox2
    image: netboxcommunity/netbox:v2.10
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    depends_on:
    - pgpool-2
    - redis-sentinel-2
    - redis-sentinel-cache-2
    - netbox-worker2
    env_file: env/netbox2.env
    user: '101'
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./initializers:/opt/netbox/initializers:z,ro
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files2:/opt/netbox/netbox/media:z
    - netbox-config2:/etc/netbox:z
    - netbox-static3:/opt/netbox/netbox/static/:z
    ports:
    - "8080"
  netbox-worker2:
    <<: *netbox2
    depends_on:
    - redis-master
    - redis-slave-0
    - redis-slave-1
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: []
  # postgres
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:13
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    ports:
      - 5435:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:13
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    ports:
      - 5436:5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pg-2:
    image: docker.io/bitnami/postgresql-repmgr:13
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    ports:
      - 5437:5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=netbox
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
  pgpool-0:
    image: docker.io/bitnami/pgpool:4
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    ports:
      - 5432:5432
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgpool-1:
    image: docker.io/bitnami/pgpool:4
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    ports:
      - 5433:5432
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgpool-2:
    image: docker.io/bitnami/pgpool:4
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    ports:
      - 5434:5432
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  # redis
  redis-master:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=Viethung1008@
    volumes:
    - netbox-redis-master-data:/bitnami/redis/data

  redis-slave-0:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
    - netbox-redis_0-data:/bitnami/redis/data

  redis-slave-1:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
    - netbox-redis_1-data:/bitnami/redis/data
  
  redis-sentinel:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-master
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26379:26379'
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-master
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26380:26379'

  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-master
      - redis-slave-0
      - redis-slave-1
    ports:
      - '26381:26379'
# redis cache 
  redis-cache-master:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=Viethung1008@

  redis-cache-slave-0:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-cache-master

  redis-cache-slave-1:
    image: 'bitnami/redis:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_PASSWORD=Viethung1008@
    ports:
      - '6379'
    depends_on:
      - redis-cache-master

  redis-sentinel-cache:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26382:26379'
  redis-sentinel-cache-1:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26383:26379'
  redis-sentinel-cache-2:
    image: 'bitnami/redis-sentinel:6.2'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    environment:
      - REDIS_MASTER_HOST=redis-cache-master
      - REDIS_MASTER_PASSWORD=Viethung1008@
      - REDIS_SENTINEL_TLS_AUTH_CLIENTS=no
    depends_on:
      - redis-cache-master
      - redis-cache-slave-0
      - redis-cache-slave-1
    ports:
      - '26384:26379'
  nginx-revserse1: 
    image: 'nginx:1.20'
    deploy:
      placement:
        constraints: [node.hostname == docker1]
    depends_on:
      - netbox
    volumes:
    - netbox-static1:/opt/netbox/netbox/static/:z,ro
    - etc-nginx1:/etc/nginx
    ports:
    - "8081:80"
    - "4431:443"
  nginx-revserse2: 
    image: 'nginx:1.20'
    deploy:
      placement:
        constraints: [node.hostname == docker2]
    depends_on:
      - netbox1
    volumes:
    - netbox-static2:/opt/netbox/netbox/static/:z,ro
    - etc-nginx2:/etc/nginx
    ports:
    - "8082:80"
    - "4432:443"
  nginx-revserse3: 
    image: 'nginx:1.20'
    deploy:
      placement:
        constraints: [node.hostname == docker3]
    depends_on:
      - netbox2
    volumes:
    - netbox-static3:/opt/netbox/netbox/static/:z,ro
    - etc-nginx3:/etc/nginx
    ports:
    - "8083:80"
    - "4433:443"
  
volumes:
  netbox-postgres-data:
    driver: local
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
  netbox-redis-master-data:
    driver: local
  netbox-redis_0-data:
    driver: local
  netbox-redis_1-data:
    driver: local
  netbox-media-files:
    driver: local
  netbox-config:
    driver: local
  netbox-media-files1:
    driver: local
  netbox-config1:
    driver: local
  netbox-media-files2:
    driver: local
  netbox-config2:
    driver: local
  netbox-static1:
    driver: local
  etc-nginx1:
    driver: local
  netbox-static2:
    driver: local
  etc-nginx2:
    driver: local
  netbox-static3:
    driver: local
  etc-nginx3:
    driver: local